# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laddr_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teams', models.ManyToManyField(to='laddr_site.Team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laddr_site.Game')),
            ],
        ),
        migrations.AddField(
            model_name='tournament_game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='playstyle',
            field=models.CharField(choices=[('Aggressive', 'Aggressive'), ('Conservative', 'Conservative'), ('Supporting', 'Supporting')], max_length=40),
        ),
        migrations.AddField(
            model_name='tournament_game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laddr_site.Tournament'),
        ),
    ]
