# Generated by Django 2.0.3 on 2018-04-19 00:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laddr_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psycograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('johnny_rank', models.IntegerField()),
                ('spike_rank', models.IntegerField()),
                ('timmy_rank', models.IntegerField()),
                ('preferred_johnny_rank', models.IntegerField()),
                ('preferred_spike_rank', models.IntegerField()),
                ('preferred_timmy_rank', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='player',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Bottom', 'Bottom'), ('Support', 'Support'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Top', 'Top')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_champions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'First': None, 'Second': None, 'Third': None}),
        ),
    ]
