# Generated by Django 2.0.3 on 2018-04-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laddr_site', '0002_auto_20180418_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psycograph',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='johnny_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_johnny_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_spike_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_timmy_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='spike_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='timmy_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Psycograph',
        ),
    ]
