# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laddr_site', '0002_auto_20180213_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout_1', to='laddr_site.Team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout_2', to='laddr_site.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bout',
            unique_together=set([('team_1', 'team_2')]),
        ),
    ]
