# Generated by Django 2.0.3 on 2018-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laddr_site', '0004_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
