# Generated by Django 2.0.3 on 2018-06-21 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laddr_site', '0005_auto_20180531_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_profiles_ranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychepreference',
            name='potential_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychepreference_potential_match', to='laddr_site.Profile'),
        ),
        migrations.AddField(
            model_name='psychepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychepreference_psyche_profile', to='laddr_site.Profile'),
        ),
    ]
